name: Push gem

on:
  workflow_run:
    workflows: ["Ruby"]
    types: ["completed"]
    branches: ["main"]

jobs:
  push:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    # - uses: rubygems/push@v1
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.2.2
    - uses: rubygems/configure-rubygems-credentials@segiddins/support-trusted-publishers
      with:
        gem-server: "https://oidc-api-token.rubygems.org"
        trusted-publisher: true
        audience: oidc-api-token.rubygems.org
    - name: Set remote URL
      run: |
        git config --global user.email "$(git log -1 --pretty=format:'%ae')"
        git config --global user.name "$(git log -1 --pretty=format:'%an')"
        git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"
    - name: Release
      run: bundle exec rake release
      env:
        GEM_HOST: "https://oidc-api-token.rubygems.org"
